CREATE TABLE show_rosters (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  show_id INTEGER NOT NULL REFERENCES shows(id) ON DELETE CASCADE,
  wrestler_id INTEGER NOT NULL REFERENCES wrestlers(id) ON DELETE CASCADE,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(show_id, wrestler_id)
);